"""Generate Chrome Web Store artwork.

Creates:
  - a less text-heavy 440x280 promotional image

The 128x128 store icon is generated by icons/generate.py.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "store-assets"

PAPER = (246, 241, 231, 255)
PAPER_ALT = (252, 248, 241, 255)
INK = (26, 25, 22, 255)
ACCENT = (37, 74, 132, 255)
ACCENT_SOFT = (221, 231, 246, 255)
RULE = (217, 209, 189, 255)
SHADOW = (0, 0, 0, 55)


def rounded_panel(size, radius, fill, outline=None, outline_width=1, shadow=False):
    w, h = size
    panel = Image.new("RGBA", size, (0, 0, 0, 0))
    if shadow:
        shadow_img = Image.new("RGBA", size, (0, 0, 0, 0))
        sd = ImageDraw.Draw(shadow_img)
        sd.rounded_rectangle((8, 8, w - 2, h - 2), radius=radius, fill=SHADOW)
        shadow_img = shadow_img.filter(ImageFilter.GaussianBlur(10))
        panel.alpha_composite(shadow_img)
    d = ImageDraw.Draw(panel)
    d.rounded_rectangle((0, 0, w - 1, h - 1), radius=radius, fill=fill, outline=outline, width=outline_width)
    return panel


def make_promo():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    img = Image.new("RGBA", (440, 280), PAPER_ALT)
    d = ImageDraw.Draw(img)

    d.rectangle((0, 0, 26, 280), fill=ACCENT)

    # Large article card on the left.
    article = rounded_panel((214, 218), 22, PAPER, outline=RULE, outline_width=2, shadow=True)
    img.alpha_composite(article, (38, 32))

    # Smaller result popup card floating on the right.
    popup = rounded_panel((170, 192), 20, PAPER, outline=RULE, outline_width=2, shadow=True)
    img.alpha_composite(popup, (246, 26))

    # Floating icon chip at the top of the article card.
    chip = rounded_panel((74, 74), 18, PAPER_ALT, outline=RULE, outline_width=2, shadow=True)
    img.alpha_composite(chip, (56, 48))
    icon = Image.open(ROOT / "icons" / "icon-128.png").convert("RGBA").resize((46, 46), Image.LANCZOS)
    img.alpha_composite(icon, (70, 62))

    # Stylized article composition: kicker, headline, selected excerpt, body.
    d.rounded_rectangle((146, 56, 210, 66), radius=4, fill=ACCENT_SOFT)
    d.rounded_rectangle((56, 136, 226, 150), radius=7, fill=INK)
    d.rounded_rectangle((56, 158, 204, 170), radius=6, fill=INK)

    # Highlighted "focus passage".
    for y in (188, 206):
        d.rounded_rectangle((56, y, 228, y + 12), radius=5, fill=ACCENT_SOFT)
    d.rounded_rectangle((56, 224, 168, 236), radius=5, fill=ACCENT_SOFT)

    # Body lines beneath the highlight.
    for width, y in ((164, 244), (148, 260)):
        d.rounded_rectangle((56, y, 56 + width, y + 7), radius=3, fill=RULE)

    # Connector from selected passage to result card.
    d.line((224, 214, 246, 182), fill=ACCENT, width=4)
    d.ellipse((220, 210, 230, 220), fill=ACCENT)
    d.polygon(((242, 182), (231, 178), (238, 191)), fill=ACCENT)

    # Popup UI cues that read more clearly as a found case result.
    d.rounded_rectangle((260, 46, 282, 60), radius=3, fill=ACCENT_SOFT)
    d.rounded_rectangle((292, 48, 348, 56), radius=3, fill=RULE)
    d.rounded_rectangle((260, 76, 394, 89), radius=6, fill=INK)
    d.rounded_rectangle((260, 98, 384, 111), radius=6, fill=INK)
    d.rounded_rectangle((260, 126, 374, 134), radius=4, fill=RULE)
    d.rounded_rectangle((260, 142, 330, 150), radius=4, fill=RULE)
    d.rounded_rectangle((260, 166, 400, 208), radius=10, fill=INK)
    d.rounded_rectangle((260, 228, 312, 238), radius=4, fill=ACCENT_SOFT)
    d.line((260, 252, 392, 252), fill=RULE, width=2)
    for x in (360, 378, 396):
        d.ellipse((x, 225, x + 8, 233), fill=ACCENT)

    img.save(OUT_DIR / "chrome-small-promo-440x280.png", "PNG", optimize=True)


if __name__ == "__main__":
    make_promo()
